micronaut:
  application:
    name: MyResturantOrderSys
  server:
    port: 8080


---
micronaut:
  views:
    thymeleaf:
      enabled: true

---
micronaut:
  router:
    static-resources:
      default:
        mapping: "/**"
      '*':
        paths:
        - "classpath:static"
---

micronaut:
  security:
    enabled: true
    intercept-url-map:
      - pattern: /api/users/register/**
        access: 
          - isAnonymous()
      - pattern: /api/restaurant/**
        access: 
          - restaurant
      - pattern: /api/menu/**
        access: 
          - restaurant
      - pattern: /api/session/**
        access:
          - restaurant
      - pattern: /A/**
        access:
          - isAnonymous()
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"

# ---

# datasources:
#   default:
#     url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#     driverClassName: org.h2.Driver
#     username: sa
#     password: ''
#     dialect: H2
# jpa:
#   default:
#     properties:
#       hibernate:
#         hbm2ddl:
#           auto: update

# ---

# redis:
#   uri: redis://localhost

# ---

# #rabbitmq:
# #  uri: amqp://localhost:5672

# ---

mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"

# ---

# datasources.default: {}
---
endpoints:
  beans:
    enabled: true
    sensitive: true 
  info:
    enabled: true
    sensitive: false  
